name       : python-uritemplate
version    : 3.0.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/cd/db/f7b98cdc3f81513fb25d3cbe2501d621882ee81150b745cdd1363278c10a/uritemplate-3.0.0.tar.gz : c02643cebe23fc8adb5e6becffe201185bf06c40bda5c0b4028a93f1527d011d
license    : Apache-2.0
component  : programming.python
summary    : URI Template Expansison
description: |
    This is a Python implementation of RFC6570, URI Template, and can expand templates up to and including Level 4 in that specification
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-simplejson
build      : |
    %python3_setup
install    : |
    %python3_install
