name       : python-uritemplate
version    : 4.1.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/d2/5a/4742fdba39cd02a56226815abfa72fe0aa81c33bed16ed045647d6000eba/uritemplate-4.1.1.tar.gz : 4346edfc5c3b79f694bccd6d6099a322bbeb628dbf2cd86eea55a456ce5124f0
license    : Apache-2.0
component  : programming.python
summary    : URI Template Expansison
description: |
    This is a Python implementation of RFC6570, URI Template, and can expand templates up to and including Level 4 in that specification
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
